### PR TITLE
Allow users to set / force the power limit as an argument

### PR DESCRIPTION
**Pull request by creolis**
This allows us to use the tool in scripts without having to deal with interactive input. In this first change the --force parameter is supported by set-power-limit.

Found no good place for adding it into help text, maybe a "help" command would come in handy ;)

### CODE REVIEW

**Comment by suaveolent** [comment]
Thanks, I will have a look at it next week.

**Comment by suaveolent** [comment]
@creolis I adressed this separately today, since you Pull Request was never updated.

you can now call the library with e.g.

`hoymiles-wifi --host <IP/Host-name> set-power-limit --disable-interactive --power-limit 100`

**Comment by creolis** [comment]
Thanks <3

**Comment by suaveolent** [comment]
You're welcome. No worries. Since I was already updating the lib i took the liberty and added the code.

**Pull request closed without merging**
